#!/bin/bash
desc=$1
filename="${1}.txt"
./mcca 1
./mcca 2
for (( i = 4 ; i <= 240 ; i= i + 4))
do
   ./mcca $i
done
mkdir results/$desc
mv *_results.txt results/$desc/.
cat results/$desc/*_results.txt > results/$desc/total.txt
sort -k 1,1 -k 2,2 -n results/$desc/total.txt > results/$desc/output.txt
